config/routes.rb
Rails.application.routes.draw do
  root "songs#index"
  resources :artists
  resources :songs do
    resources :billboards, only: [:index, :new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :billboards, dependent: :destroy
  has_many :songs, through: :billboards

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  belongs_to :artist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :billboards, dependent: :destroy
  has_many :artists, through: :billboards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end


  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      # redirect_to artist_path(@artist)
      redirect_to @artist
    else
      render :new
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path

  end

  private
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:first_name, :last_name)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
before_action :set_song

  def index
    @us_100s = @song.billboards.where(top: 'us_100')
    @euro_100s = @song.billboards.where(top: 'euro_100')
  end

  def new
    @artist = Artist.all - @song.artists
    @billboards = @song.billboards.new
  end

  private
  def set_song
    @song = Song.find(params[:song_id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if@song.save
      redirect_to @song
    else
      render :new
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>
<%= link_to 'Add Artist +', new_artist_path %>
<hr />
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.full_name, artist %>
    </li>
<% end %>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1><%= @artist.full_name %></h1>
<hr />
<h2>Songs</h2>
<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to song.name, song %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete Artist', @artist, method: :delete, class: "ui red button inverted" %>

app/views/billboards/index.html.erb
<h1><%= @song.name %>: Music Billboard</h1>
<%= link_to 'Add BillBoard', new_song_billboard_path(@song) %>
<hr />

<h2>US TOP 100</h2>
<ul>
  <% @us_100s.each do |us| %>
    <li>
      <%= us.artist.full_name %>
      <br />
    </li>
    <%= link_to 'Remove', song_billboard_path(@song, us), method: :delete %>
  <% end %>
</ul>

<h2>Euro TOP 100</h2>
<ul>
  <% @euro_100s.each do |euro| %>
    <li>
      <%= euro.artist.full_name %>
      <br />
    </li>
      <%= link_to 'Remove', song_billboard_path(@song, euro), method: :delete %>
 <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Add to Billboard</h1>

<%= form_with(model: [@song, @billboard], local: :true) do |f|%>
  <%= f.label :artist%>
  <%= f.select :artist_id, @artists.collect { |u| [u.full_name, u.id]}%>
  <br/>
  <%= f.label :top%>
  <%= f.select :top, ['us_100','euro_100']%>
  <br/>
  <%= f.submit nil, class:'button'%>
<%end%>

app/views/layouts/_navbar.html.erb
<div class="ui secondary  menu">
  <a class="active item">
    <%= link_to 'Songs', songs_path %>
  </a>
  <a class="item">
   <%= link_to 'Add Song', new_song_path %>
  </a>
  <a class="item">
   <%= link_to 'Artists', artists_path %>
  </a>
  <a class="item">
   <%= link_to 'Add Artist', new_artist_path %>
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <a class="ui item">
      Logout
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>


  <%# <div class="ui pointing menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui transparent icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
  </div>
</div>
<div class="ui segment">
  <p></p>
</div> %>

app/views/songs/index.html.erb
<h1 class="ui center aligned icon header">Billboard Top 100</h1>
<%# <%= link_to "Add Song +", new_song_path%> 
<br/>
<h2> <%=@songs.length <= 0 ? "No Songs" : ""%> </h2>

<div class="ui center aligned icon header">
<ul>
  <% @songs.each do |song|%>
    <li class="ui list">
    <%= link_to song.name, artist_path(song)%>
     </li>
  <%end%>
</ul>
</div>

app/views/songs/new.html.erb
<h1>Add Songs</h1>
<%= form_with(model: @song, local: true, class:'ui form') do |f|%>

<div class='field'>
  <%=f.label :name %>
  <%=f.text_field :name , required: true, placeholder: "Song Name"%>
</div>
<%=f.submit nil, class:'ui blue button inverted'%>
<%end%>

app/views/songs/show.html.erb
<h1><%= @song.name%></h1>
<hr/>

<%= link_to 'Billboards', song_billboards_path(@song), class: 'ui button '%>